export const GAME_CONCEPTS = [
  "Gestión Técnica",
  "Fase de Operación",
  "Conocimiento TI",
  "Recursos Humanos",
  "Instrumentos Administrativos",
  "Políticas de Personal",
  "Mejora Continua",
  "Factor Ambiental",
  "Manejo Ambiental Seguro",
  "Residuales",
  "Necesidad",
  "Deseo",
  "Satisfactor",
  "Oportunidad de Negocio",
  "Gestión de Company Cars",
  "Sostenibilidad",
  "Calidad Total",
  "Hardware",
  "Control Interno",
  "Estrategia Ambiental",
  "Diagnóstico Comunitario",
  "Ciclo de Vida",
  "Reingeniería",
  "Gestión de Procesos"
];

export const CONCEPT_DEFINITIONS: Record<string, string> = {
  "Gestión Técnica": "Es la encargada de aportar las habilidades y los recursos necesarios para dar soporte a la fase de Operación del servicio, participando también en el diseño y mejora de los servicios TI.",
  "Fase de Operación": "Es la fase más crítica entre todas, donde la percepción de los clientes depende de una correcta organización y coordinación de los agentes involucrados.",
  "Conocimiento TI": "Debe ser identificado, distribuido y perfeccionado para diseñar, probar y mejorar la infraestructura técnica de la empresa.",
  "Recursos Humanos": "Área más relevante en una empresa, responsable de desarrollar, movilizar y motivar al personal empleado.",
  "Instrumentos Administrativos": "El apoyo necesario y obligatorio para conseguir, desarrollar y conservar los recursos de una empresa; sin ellos no se pueden ejecutar las políticas del personal.",
  "Políticas de Personal": "Normativas utilizadas para que el personal pueda ponerse en funcionamiento, articulando las funciones sociales con las metas que posee la empresa.",
  "Mejora Continua": "Principio bajo el cual deben trabajar industrias con problemas ambientales desarrollados durante décadas, disminuyendo costos y eliminando impactos negativos.",
  "Factor Ambiental": "Elemento cuya inclusión es exigida imperativamente para garantizar la competitividad de una empresa y su supervivencia a mediano y largo plazo.",
  "Manejo Ambiental Seguro": "Ingrediente esencial para alcanzar la sustentabilidad, minimizando residuales y teniendo en cuenta técnicas modernas en operaciones industriales.",
  "Residuales": "Desechos que deben ser minimizados obligatoriamente logrando un equilibrio entre desarrollo y medio ambiente.",
  "Necesidad": "Sensación de carencia indispensable para la conservación y desarrollo de un ser vivo, asociada al esfuerzo por suprimir esta falta (ej. la sed).",
  "Deseo": "Es una necesidad que ha tomado la forma específica de un producto, marca o empresa.",
  "Satisfactor": "Producto o servicio desarrollado por la empresa con el fin de cubrir una carencia y despertar el deseo del consumidor.",
  "Oportunidad de Negocio": "Situación que ocurre cuando el marketing detecta necesidades existentes y las transforma en beneficios para la empresa.",
  "Gestión de Company Cars": "Evaluación técnica que consiste en verificar el estado físico, kilometraje y daños de vehículos devueltos a la flota de la empresa.",
  "Sostenibilidad": "Capacidad de satisfacer las necesidades actuales sin comprometer las de las futuras generaciones.",
  "Calidad Total": "Sistema de gestión que involucra a todos los miembros de la organización en la mejora continua de productos y procesos.",
  "Hardware": "Todos los productos tangibles de la informática; la parte física de un equipo de cómputo.",
  "Control Interno": "Poderoso elemento de ayuda a la gestión que evita fraudes y asegura el cumplimiento de objetivos.",
  "Estrategia Ambiental": "Pautas que conducen a un estadio superior en la protección del medio ambiente y el uso racional de recursos.",
  "Diagnóstico Comunitario": "Evaluación de las carencias y necesidades de un grupo social respecto a servicios o productos.",
  "Ciclo de Vida": "Fases por las que pasa un servicio TI desde su concepción hasta su retiro.",
  "Reingeniería": "Revisión fundamental y rediseño radical de procesos para alcanzar mejoras espectaculares en medidas críticas.",
  "Gestión de Procesos": "Herramienta para la creación de valor y el incremento de la productividad a través del análisis de experiencias prácticas."
};